const foodNames = [
  "artichok", 
  "arugula", 
  "asparagu", 
  "aubergin", 
  "amaranth", 
  "legum", 
  "alfalfa sprout", 
  "azuki bean", 
  "bean sprout", 
  "black bean", 
  "black eye pea", 
  "black-ey pea", 
  "borlotti bean", 
  "broad bean", 
  "chickpea", 
  "garbanzo", 
  "ceci bean", 
  "green bean", 
  "kidney bean", 
  "lentil", 
  "lima bean", 
  "butter bean", 
  "mung bean", 
  "navi bean", 
  "pinto bean", 
  "runner bean", 
  "split pea", 
  "soy bean", 
  "pea", 
  "mangetout", 
  "snap pea", 
  "beet green", 
  "bok choy", 
  "broccoflow", 
  "broccoli", 
  "brussel sprout", 
  "cabbag", 
  "calabres", 
  "carrot", 
  "cauliflow", 
  "celeri", 
  "chard", 
  "collard green", 
  "corn salad", 
  "endiv", 
  "fiddlehead", 
  "frise", 
  "fennel", 
  "anis", 
  "basil", 
  "caraway", 
  "cilantro seed", 
  "coriand", 
  "chamomil", 
  "dill", 
  "fennel", 
  "lavend", 
  "lemon grass", 
  "marjoram", 
  "oregano", 
  "parsley", 
  "rosemari", 
  "sage", 
  "thyme", 
  "kale", 
  "kohlrabi", 
  "lettuc lactuca sativa", 
  "maiz", 
  "mushroom", 
  "mustard green", 
  "nettl", 
  "new zealand spinach", 
  "okra", 
  "chive", 
  "garlic", 
  "leek allium porrum", 
  "onion", 
  "shallot", 
  "spring onion", 
  "parsley", 
  "pepper", 
  "green pepper", 
  "red pepper", 
  "bell pepper", 
  "pimento", 
  "chili pepper", 
  "jalapeño", 
  "habanero", 
  "paprika", 
  "tabasco pepper", 
  "cayenn pepper", 
  "radicchio", 
  "rhubarb", 
  "root veget", 
  "beetroot", 
  "carrot", 
  "celeriac", 
  "daikon", 
  "ginger", 
  "parsnip", 
  "rutabaga", 
  "turnip", 
  "radish", 
  "swede", 
  "turnip", 
  "wasabi", 
  "horseradish", 
  "white radish", 
  "salsifi", 
  "skirret", 
  "spinach", 
  "topinambur", 
  "squash", 
  "acorn squash", 
  "butternut squash", 
  "banana squash", 
  "courgett", 
  "cucumb", 
  "delicata", 
  "gem squash", 
  "hubbard squash", 
  "marrow", 
  "patti pan", 
  "pumpkin", 
  "spaghetti squash", 
  "tat soi", 
  "tomato", 
  "tuber", 
  "jicama", 
  "jerusalem artichok", 
  "potato", 
  "sunchok", 
  "sweet potato", 
  "taro", 
  "yam", 
  "turnip green", 
  "water chestnut", 
  "watercress", 
  "zucchini", 
  "appl", 
  "apricot", 
  "avocado", 
  "banana", 
  "blackcurr", 
  "currant", 
  "cherimoya", 
  "coconut", 
  "cucumb", 
  "custard appl", 
  "damson", 
  "date", 
  "dragonfruit", 
  "durian", 
  "feijoa", 
  "fig", 
  "grape", 
  "raisin", 
  "grapefruit", 
  "guava", 
  "jabuticaba", 
  "jackfruit", 
  "jambul", 
  "jujub", 
  "kiwifruit", 
  "kumquat", 
  "lemon", 
  "lime", 
  "loquat", 
  "longan", 
  "lyche", 
  "mango", 
  "melon", 
  "cantaloup", 
  "honeydew", 
  "watermelon", 
  "miracl fruit", 
  "nectarin", 
  "nanc", 
  "oliv", 
  "orang", 
  "blood orang", 
  "clementin", 
  "mandarin", 
  "tangerin", 
  "papaya", 
  "passionfruit", 
  "peach", 
  "pear", 
  "persimmon", 
  "physali", 
  "plantain", 
  "plum", 
  "prune", 
  "dri plum", 
  "pineappl", 
  "plumcot", 
  "pluot", 
  "pomegran", 
  "pomelo", 
  "purpl mangosteen", 
  "quinc", 
  "bilberri", 
  "blackberri", 
  "blueberri", 
  "cherri", 
  "cranberri", 
  "cloudberri", 
  "elderberri", 
  "goji berri", 
  "gooseberri", 
  "boysenberri", 
  "honeyberri", 
  "huckleberri", 
  "junip berri", 
  "marionberri", 
  "mulberri", 
  "raspberri", 
  "salmonberri", 
  "strawberri", 
  "salal berri", 
  "bilberri", 
  "blackberri", 
  "blueberri", 
  "cherri", 
  "cranberri", 
  "cloudberri", 
  "elderberri", 
  "goji berri", 
  "gooseberri", 
  "boysenberri", 
  "honeyberri", 
  "huckleberri", 
  "junip berri", 
  "marionberri", 
  "mulberri", 
  "raspberri", 
  "salmonberri", 
  "strawberri", 
  "salal berri", 
  "rambutan", 
  "redcurr", 
  "salak", 
  "satsuma", 
  "soursop", 
  "star fruit", 
  "solanum quitoens", 
  "tamarillo", 
  "tamarind", 
  "ugli fruit", 
  "yuzu"
]

exports.getNatural = function(name) {
  const stemmer = require('porter-stemmer').stemmer
  const sname = stemmer(name)
  return foodNames.indexOf(sname)
}
