const foodNames = [
  "artichoke",
  "arugula",
  "asparagus",
  "aubergine",
  "amaranth",
  "legumes",
  "alfalfa sprouts",
  "azuki beans",
  "bean sprouts",
  "black beans",
  "black eyed peas",
  "black-eyed peas",
  "borlotti bean",
  "broad beans",
  "chickpeas",
  "garbanzos",
  "ceci beans",
  "green beans",
  "kidney beans",
  "lentils",
  "lima beans",
  "butter bean",
  "mung beans",
  "navy beans",
  "pinto beans",
  "runner beans",
  "split peas",
  "soy beans",
  "peas",
  "mangetout",
  "snap peas",
  "beet greens",
  "bok choy",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrots",
  "cauliflower",
  "celery",
  "chard",
  "collard greens",
  "corn salad",
  "endive",
  "fiddleheads",
  "frisee",
  "fennel",
  "anise",
  "basil",
  "caraway",
  "cilantro seeds",
  "coriander",
  "chamomile",
  "dill",
  "fennel",
  "lavender",
  "lemon grass",
  "marjoram",
  "oregano",
  "parsley",
  "rosemary",
  "sage",
  "thyme",
  "kale",
  "kohlrabi",
  "lettuce lactuca sativa",
  "maize",
  "mushrooms",
  "mustard greens",
  "nettles",
  "new zealand spinach",
  "okra",
  "onion family",
  "chives",
  "garlic",
  "leek allium porrum",
  "onion",
  "shallot",
  "spring onion",
  "parsley",
  "peppers",
  "green pepper",
  "red pepper",
  "bell pepper",
  "pimento",
  "chili pepper",
  "jalapeño",
  "habanero",
  "paprika",
  "tabasco pepper",
  "cayenne pepper",
  "radicchio",
  "rhubarb",
  "root vegetables",
  "beetroot",
  "carrot",
  "celeriac",
  "daikon",
  "ginger",
  "parsnip",
  "rutabaga",
  "turnip",
  "radish",
  "swede",
  "turnip",
  "wasabi",
  "horseradish",
  "white radish",
  "salsify",
  "skirret",
  "spinach",
  "topinambur",
  "squashes",
  "acorn squash",
  "butternut squash",
  "banana squash",
  "courgette",
  "cucumber",
  "delicata",
  "gem squash",
  "hubbard squash",
  "marrow",
  "patty pans",
  "pumpkin",
  "spaghetti squash",
  "tat soi",
  "tomato",
  "tubers",
  "jicama",
  "jerusalem artichoke",
  "potato",
  "sunchokes",
  "sweet potato",
  "taro",
  "yam",
  "turnip greens",
  "water chestnut",
  "watercress",
  "zucchini",
  "apple",
  "apricot",
  "avocado",
  "banana",
  "bilberry",
  "blackberry",
  "blackcurrant",
  "blueberry",
  "boysenberry",
  "currant",
  "cherry",
  "cherimoya",
  "cloudberry",
  "coconut",
  "cranberry",
  "cucumber",
  "custard apple",
  "damson",
  "date",
  "dragonfruit",
  "durian",
  "elderberry",
  "feijoa",
  "fig",
  "goji berry",
  "gooseberry",
  "grape",
  "raisin",
  "grapefruit",
  "guava",
  "honeyberry",
  "huckleberry",
  "jabuticaba",
  "jackfruit",
  "jambul",
  "jujube",
  "juniper berry",
  "kiwifruit",
  "kumquat",
  "lemon",
  "lime",
  "loquat",
  "longan",
  "lychee",
  "mango",
  "marionberry",
  "melon",
  "cantaloupe",
  "honeydew",
  "watermelon",
  "miracle fruit",
  "mulberry",
  "nectarine",
  "nance",
  "olive",
  "orange",
  "blood orange",
  "clementine",
  "mandarine",
  "tangerine",
  "papaya",
  "passionfruit",
  "peach",
  "pear",
  "persimmon",
  "physalis",
  "plantain",
  "plum",
  "prune",
  "dried plum",
  "pineapple",
  "plumcot",
  "pluot",
  "pomegranate",
  "pomelo",
  "purple mangosteen",
  "quince",
  "raspberry",
  "salmonberry",
  "rambutan",
  "redcurrant",
  "salal berry",
  "salak",
  "satsuma",
  "soursop",
  "star fruit",
  "solanum quitoense",
  "strawberry",
  "tamarillo",
  "tamarind",
  "ugli fruit",
  "yuzu"
]

exports.getNatural = function(name) {
  return foodNames.indexOf(name) || foodNames.indexOf(name + 's')
}
